### ISSUE TITLE
私有仓库的镜像显示错位

### ISSUE THREAD

**Issue by kenhq03** [lioncui/dockmaster#2]
私有仓库的镜像，镜像名称里面带有冒号，例如172.1.1.1:5000/test-ssh:latest，在镜像查看里面，会错位显示如下，
REPOSITORY-->172.21.101.102 
TAG --> 5000/test-ssh
ID --> latest
...

**Comment by lioncui** [comment]
代码已经修复了这个BUG,只是docker image我还没有更新,你可以clone下来 自己 docker build -t . 构建一个最新的镜像就好了,感谢使用.

**Comment by lioncui** [comment]
dockerhub的镜像也更新了,感谢使用
